/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_alaskanemily_jopus_JOpus */

#ifndef _Included_net_alaskanemily_jopus_JOpus
#define _Included_net_alaskanemily_jopus_JOpus
#ifdef __cplusplus
extern "C" {
#endif
#undef net_alaskanemily_jopus_JOpus_defaultSampleRate
#define net_alaskanemily_jopus_JOpus_defaultSampleRate 48000L
/*
 * Class:     net_alaskanemily_jopus_JOpus
 * Method:    Construct
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_net_alaskanemily_jopus_JOpus_Construct
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_alaskanemily_jopus_JOpus
 * Method:    decode
 * Signature: (J[BILjava/lang/Class;)Ljava/nio/ShortBuffer;
 */
JNIEXPORT jobject JNICALL Java_net_alaskanemily_jopus_JOpus_decode
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jclass);

/*
 * Class:     net_alaskanemily_jopus_JOpus
 * Method:    decodeFloat
 * Signature: (J[BILjava/lang/Class;)Ljava/nio/FloatBuffer;
 */
JNIEXPORT jobject JNICALL Java_net_alaskanemily_jopus_JOpus_decodeFloat
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jclass);

/*
 * Class:     net_alaskanemily_jopus_JOpus
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_alaskanemily_jopus_JOpus_destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
